### ISSUE TITLE
Trying to use a discord-account with default avatar causes argument null error

### ISSUE THREAD

**Issue by EngineLessCC** [crybapp/api#71]
Can be fixed by setting a profile picture at discord account settings
Log snippet:
> New login from origin http://127.0.0.1:3000
Error: Illegal argument null
    at Object.module.exports [as default] (...\cryb2\api\node_modules\md5\md5.js:152:13)
    at Object.exports.constructAvatar (...\cryb2\api\dist\services\oauth2\discord.service.js:13:64)
    at ...\cryb2\api\dist\models\user\index.js:47:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
POST /auth/discord 500 414.150 ms - 21

**Comment by 69** [comment]
This error appears to be due to no email being set rather than no avatar being set: 
https://github.com/crybapp/api/blob/c02e379642d6e480b8ca69ad44bf8b166c28d180/src/services/oauth2/discord.service.ts#L25

**Comment by JeDaYoshi** [comment]
Thanks for reporting this!
